src/account/urls.py
# # -*- coding: utf-8 -*-

# from django.conf.urls import patterns, url

# ################################################################################

# urlpatterns = patterns('project.auth.views',
#     url(r'^login/$', "login_view", name='login'),
#     url(r'^logout/$', "logout_view", name='logout'),
# )


# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.conf.urls import patterns, url

urlpatterns = patterns('',

    url(r'^login/$',
        'django.contrib.auth.views.login', {
            'template_name': 'account/login.html'
        },
        name="login"
        ),

    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {"next_page": "/"},
        name='logout'
        ),

    # url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    # url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    # url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    # url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     'django.contrib.auth.views.password_reset_confirm',
    #     name='password_reset_confirm'),
    # url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
)

src/event/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from event import views as event_views

################################################################################


urlpatterns = patterns('event.views',
    url(r'^$', login_required(event_views.DashboardView.as_view()), name="dashboard"),
    url(r'^set-dashboard-start/(?P<date_arg>\d{4}-\d{2}-\d{2})$', login_required(event_views.setDashboardStart), name="set-dashboard-start"),
    url(r'^set-dashboard-end/(?P<date_arg>\d{4}-\d{2}-\d{2})$', login_required(event_views.setDashboardEnd), name="set-dashboard-end"),
    url(r'^reset-dashboard-dates$', login_required(event_views.resetDashboardDates), name="reset-dashboard-dates"),
    url(r'^event-add/(?P<start>\d{4}-\d{2}-\d{2})?$', login_required(event_views.EventCreate.as_view()), name="event-create"),
    # url(r'^event/(?P<pk>[0-9]+)$', login_required(event_views.eventDetail), name="event-detail"),
    url(r'^event/(?P<pk>[0-9]+)$', login_required(event_views.EventDetail.as_view()), name="event-detail"),
    url(r'^event/(?P<pk>[0-9]+)/update$', login_required(event_views.EventUpdate.as_view()), name="event-update"),
    url(r'^event/(?P<pk>[0-9]+)/delete$', login_required(event_views.EventDelete.as_view()), name="event-delete"),
    url(r'^event/(?P<pk>[0-9]+)/items$', login_required(event_views.EventItemList.as_view()), name="event-items"),
    url(r'^event/(?P<pk>[0-9]+)/book-all-possible$', login_required(event_views.bookAllPossible), name="book-all-possible"),

    # url(r'^event/(?P<pk>[0-9]+)/items$', login_required(event_views.EventItemList.as_view()), name="event-items"),
    # url(r'^event/(?P<pk>[0-9]+)/items$', login_required(event_views.EventItemList.as_view()), name="event-items"),

    # url(r'^event/(?P<pk>[0-9]+)/items/api/event/?$', event_views.EventItemListCreateView.as_view(), name="event-item-list-create"),
    # url(r'^event/(?P<pk>[0-9]+)/items/api/event/(?P<pk>\d+)/?$', event_views.EventItemView.as_view(), name="event-item-list-create")

    url(r'^api/event/(?P<event_pk>[0-9]+)/item/?$', login_required(event_views.EventItemListCreateView.as_view()), name="api-event-item-create"),
    url(r'^api/event/(?P<event_pk>[0-9]+)/item/(?P<pk>\d+)/?$', login_required(event_views.EventItemRetrieveUpdateDestroyView.as_view()), name="api-event-item-update")

)

src/stock/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from django.views.generic.list import ListView
# from rest_framework import routers

from stock import views as stock_views
from .models import Item

################################################################################

# router = routers.SimpleRouter()
# router.register(r'stock', login_required(stock_views.StockViewSet))


urlpatterns = patterns('stock.views',
    url(r'^stock/?$', login_required(ListView.as_view(
        model = Item,
        # paginate_by = 2,
        queryset = Item.objects.all(),
        context_object_name = 'items',
        template_name = 'stock/item_list.html',
        )), name="list"),

    url(r'^stock-item/add/?$', login_required(stock_views.ItemCreate.as_view()), name="item-create"),
    # url(r'^stock/(?P<pk>[0-9]+)$', login_required(event_views.EventDetail.as_view()), name="item-detail"),
    url(r'^stock-item/(?P<pk>[0-9]+)/update$', login_required(stock_views.ItemUpdate.as_view()), name="item-update"),
    url(r'^stock-item/(?P<pk>[0-9]+)/delete$', login_required(stock_views.ItemDelete.as_view()), name="item-delete"),


    # url(r'^api2/', include(router.urls)),
    url(r'^api/stock/?$', login_required(stock_views.ItemListAPIView.as_view()), name="api-stock-items"),
    url(r'^api/stock/(?P<pk>[0-9]+)/?$', login_required(stock_views.ItemRetrieveAPIView.as_view()), name="api-stock-item"),

    # url(r'^api/event/(?P<event_pk>[0-9]+)/item/?$', login_required(event_views.EventItemListCreateView.as_view()), name="api-event-item-create"),
    # url(r'^api/event/(?P<event_pk>[0-9]+)/item/(?P<pk>\d+)/?$', login_required(event_views.EventItemRetrieveUpdateDestroyView.as_view()), name="api-event-item-update")



)

src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth import urls as auth_urls

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('account.urls', namespace='account')),
    url(r'', include('event.urls', namespace='event')),
    url(r'', include('stock.urls', namespace='stock')),
    url(r'', include('contact.urls', namespace='contact')),

)\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/base/models.py
from django.core import urlresolvers
from django.contrib.contenttypes.models import ContentType
from django.db import models

# TODO
class IsNotDeletedManager(models.Manager):
    def get_queryset(self):
        return super(IsNotDeletedManager, self).get_queryset().filter(is_deleted=False)


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno")
    changed_at = models.DateTimeField(auto_now=True, verbose_name="Změněno")
    changed_by = models.CharField(max_length=100, default="[unknown]", verbose_name="Změnil")
    is_deleted = models.BooleanField(default=False, verbose_name='Je smazáno')

    # for admin and sys calls set default manager
    admin_objects = models.Manager()
    # for frontend filter out deleted items
    objects = IsNotDeletedManager()

    class Meta:
        abstract = True

    def __str__(self):
        return "%s%s" % (
            "DEL " if self.is_deleted else "",
            self.get_str(),
        )

    def get_str(self):
        raise NotImplementedError()

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model), args=(self.id,))

    def save_by(self, username):
        self.changed_by = username
        self.save()

src/base/forms.py
from django import forms

class BaseModelForm(forms.ModelForm):
    pass

src/base/templates/base.html
<!doctype html>{% load static from staticfiles  %}{% load l10n %}
<html class="no-js" lang="cs"{% block htmlattr %}{% endblock %}>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock %} | Ferman</title>
        <link rel="stylesheet" href="{% static "css/foundation.min.css" %}" />
        <link rel="stylesheet" href="{% static "css/foundation-datepicker.css" %}" />
        <script src="{% static "js/vendor/modernizr.js" %}"></script>
        {% block startstatic %}
        {% endblock %}
        <link rel="stylesheet" href="{% static "css/ferman.css" %}" />
    </head>
    <body>

        {% if request.user.is_authenticated %}
            <div class="row">
                {% include "menu.html" %}
    {% comment %}
                <ul class="breadcrumbs">
                    {% block breadcrumbs %}
                        <li><a href="{% url 'event:dashboard' %}">Kalendář</a></li>
                    {% endblock %}
                </ul>
    {% endcomment %}
            </div>
        {% endif %}

            {% block messages %}
                {% if messages %}
                <div class="row">
                    {% for message in messages %}
                    <div class="large-12 columns">
                        <div data-alert class="alert-box {{ message.tags }} radius">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            {% endblock %}

        <div class="row">
            <div class="medium-10 medium-offset-1 columns">
            {% block content %}{% endblock %}
            </div>
        </div>

        {% block endstatic %}
            <script src="{% static "js/vendor/jquery.js" %}"></script>
            <script src="{% static "js/foundation.min.js" %}"></script>
            <script>
                $(document).foundation();
            </script>
        {% endblock %}
    </body>
</html>

src/base/templates/menu.html
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class="name">
            <h1><a href="{% url 'event:dashboard' %}">FERMAN</a></h1>
        </li>
    </ul>

    <section class="top-bar-section">
        <ul class="left">
            <li class="divider"></li>
            <li>
                <a href="{% url 'event:dashboard' %}">Kalendář</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="{% url 'stock:list' %}">Sklad</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="{% url 'contact:list' %}">Kontakty</a>
            </li>
        </ul>

        <ul class="right">
            <li>
                <a href="{% url 'account:logout' %}">Odhlásit</a>
            </li>
        </ul>
    </section>
</nav>