src/contact/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from django.views.generic.list import ListView

from contact import views as contact_views
from .models import Contact

################################################################################


urlpatterns = patterns('contact.views',
    # url(r'^contacts$', login_required(contact_views.ContactView.as_view()), name="list"),

    url(r'^contact/?$', login_required(ListView.as_view(
        model = Contact,
        # paginate_by = 2,
        queryset = Contact.objects.all(),
        context_object_name = 'contacts',
        template_name = 'contact/contact_list.html',
        )), name="list"),

    url(r'^contact/add/?$', login_required(contact_views.ContactCreate.as_view()), name="contact-create"),
    # url(r'^contact/(?P<pk>[0-9]+)$', login_required(event_views.EventDetail.as_view()), name="contact-detail"),
    url(r'^contact/(?P<pk>[0-9]+)/update$', login_required(contact_views.ContactUpdate.as_view()), name="contact-update"),
    url(r'^contact/(?P<pk>[0-9]+)/delete$', login_required(contact_views.ContactDelete.as_view()), name="contact-delete"),


)

src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth import urls as auth_urls

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('account.urls', namespace='account')),
    url(r'', include('event.urls', namespace='event')),
    url(r'', include('stock.urls', namespace='stock')),
    url(r'', include('contact.urls', namespace='contact')),

)\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/contact/models.py
from django.db import models
from django.conf import settings

from base.models import BaseModel


class Skill(models.Model):
    name = models.CharField(unique=True, max_length=200, verbose_name="název")
    position = models.IntegerField(verbose_name="pořadí")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position', )
        verbose_name = "dovednost kontaktu"
        verbose_name_plural = "dovednosti kontaktu"


class Contact(BaseModel):
    name = models.CharField(unique=True, max_length=200, verbose_name="jméno")
    is_customer = models.BooleanField(default=False, blank=True, verbose_name="zákazník")
    phone = models.CharField(blank=True, max_length=200, verbose_name="telefon")
    email = models.EmailField(blank=True, verbose_name="email")
    remark = models.TextField(blank=True, verbose_name="poznámka")
    account = models.OneToOneField(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="login")
    # company = models.ForeignKey(Company, blank="true", null="true")
    skills = models.ManyToManyField(Skill, blank=True, verbose_name="dovednosti")

    def get_str(self):
        return self.name

    def get_skills_text(self):
        return ", ".join([skill.name for skill in self.skills.all()])
    get_skills_text.short_description = "dovednosti"

    def get_remark_text(self):
        diplayed_chars = 80
        ending = ""
        if len(self.remark) > diplayed_chars:
            ending = "…"
        return "%s%s" % (self.remark[:diplayed_chars], ending)
    get_remark_text.short_description = "poznámka"

    class Meta:
        ordering = ('name', )
        verbose_name = "kontakt"
        verbose_name_plural = "kontakty"

src/contact/forms.py
from django import forms

from .models import Contact

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = [
            'name',
            'phone',
            'email',
            'remark',
            'is_customer',
            'skills'
        ]

src/contact/views.py
# from django.shortcuts import render, redirect
# from django.views.generic import TemplateView #, View #, DetailView, View
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from django.views.generic.edit import UpdateView

from .forms import ContactForm
from .models import Contact



# class ContactView(TemplateView):
#     template_name = "list.html"

#     def get_context_data(self, **kwargs):
#         kwargs = super(ContactView, self).get_context_data(**kwargs)

#         kwargs.update({
#             "contacts": Contact.objects.all(),
#         })

#         return kwargs


class ContactDelete(DeleteView):
    model = Contact
    success_url = reverse_lazy('contact:list')

    def delete(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object and then
        redirects to the success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = True
        self.object.save_by(request.user.username)
        return HttpResponseRedirect(success_url)


class ContactCreate(CreateView):
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('contact:list')

    def form_valid(self, form):
        form.instance.changed_by = self.request.user.username
        return super(ContactCreate, self).form_valid(form)


class ContactUpdate(UpdateView):
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('contact:list')


    def form_valid(self, form):
        form.instance.changed_by = self.request.user.username
        return super(ContactUpdate, self).form_valid(form)

src/contact/templates/contact/contact_confirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles  %}

{% block title %}{{ contact.username }}{% endblock %}


{% block content %}
    <div class="row">
        <div class="large-12 columns">
        <h1>{{ contact.name }}</h1>
        </div>
    </div>

    <form action="" method="post">{% csrf_token %}
        <div class="row">
            <div class="large-8 large-offset-2 medium-10 medium-offset-1 columns">
                <p>Opravdu chcete tento kontakt smazat?</p>
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns">
                <div class="right">
                    <button type="submit" class="right button alert">Smazat</button>
                    <a href="{% url 'contact:list' %}" class="button secondary">Zrušit</a>
                </div>
            </div>
        </div>
    </form>


{% endblock %}

src/contact/templates/contact/contact_form.html
{% extends "base.html" %}
{% load static from staticfiles  %}
{% load addclass %}

{% block title %}{% if contact %}{{ contact.name }} &ndash; upravit kontakt{% else %}Přidat kontakt{% endif %}{% endblock %}


{% block content %}
    <div class="row">
        <div class="large-12 columns">

        {% if contact %}
        <h1>{{ contact.name }} &ndash; upravit kontakt</h1>
        {% else %}
        <h1>Přidat kontakt</h1>
        {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
        <form action="{% if contact %}{% url 'contact:contact-update' pk=contact.id %}{% else %}{% url 'contact:contact-create' %}{% endif %}" method="post">
            {% csrf_token %}

            <div class="row">
                <div class="large-8 large-offset-2 medium-10 medium-offset-1 columns">

                {% if form.non_field_errors %}
                    <div class="alert-box warning">
                        {{ form.non_field_errors|join:"<br>" }}
                    </div>
                {% endif %}

                <table class="form topped wide">
                    <tr>
                        <th colspan="2">
                            {{ form.name.label_tag }}
                        </th>
                    </tr>
                    <tr>
                        <td colspan="2">
                            {{ form.name }}
                            {% if form.name.errors %}
                                <div class="alert-box warning">
                                    {{ form.name.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <th>
                            {{ form.phone.label_tag }}
                        </th>
                        <th>
                            {{ form.email.label_tag }}
                        </th>
                    </tr>
                    <tr>
                        <td class="nowrap" width="30%">
                            {{ form.phone }}
                            {% if form.phone.errors %}
                                <div class="alert-box alert">
                                    {{ form.phone.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                        <td>
                            {{ form.email }}
                            {% if form.email.errors %}
                                <div class="alert-box warning">
                                    {{ form.email.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <th colspan="2">
                            {{ form.remark.label_tag }}
                        </th>
                    </tr>
                    <tr>
                        <td colspan="2">
                            {{ form.remark }}
                            {% if form.remark.errors %}
                                <div class="alert-box warning">
                                    {{ form.remark.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <th>
                            {{ form.is_customer.label_tag }}
                        </th>
                        <th>
                            {{ form.skills.label_tag }}
                        </th>
                    </tr>
                    <tr>
                        <td>
                            {{ form.is_customer }}
                            {% if form.is_customer.errors %}
                                <div class="alert-box warning">
                                    {{ form.is_customer.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                        <td>
                            {{ form.skills|addclass:'skills-widget' }}
                            {% if form.skills.errors %}
                                <div class="alert-box warning">
                                    {{ form.skills.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                </table>

                </div>
            </div>

            <div class="right">
                <button type="submit" class="right button success">Uložit</button>
                <a href="{% url 'contact:list' %}" class="button secondary">Zrušit</a>
            </div>
            {% if contact %}
            <div class="left">
                <a href="{% url 'contact:contact-delete' pk=contact.id %}" class="tiny button alert">Smazat</a>
            </div>
            {% endif %}
        </form>
        </div>
    </div>


    {% if contact %}
    <div class="row text-right">
        <div class="large-12 columns">
        <p><small>Naposledy kontakt upravil {{ contact.changed_at|date:"j. n. Y H:i" }} uživatel {{ contact.changed_by }}.</small></p>
        </div>
    </div>
    {% endif %}


{% endblock %}

src/contact/templates/contact/contact_list.html
{% extends "base.html" %}
{% load static from staticfiles  %}


{% block title %}Kontakty{% endblock %}




{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <div class="right">
                <a href="{% url 'contact:contact-create' %}" class="button success">Přidat kontakt</a>
            </div>
            <h1>Kontakty</h1>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">


            <table class="wide">
                <tr>
                    <th>
                        Jméno
                    </th>
                    <th class="text-center">
                        Telefon
                    </th>
                    <th class="text-center">
                        Email
                    </th>
                    <th class="text-center">
                        Dovednosti
                    </th>
                    <th class="text-center">
                        Změnit
                    </th>
                </tr>
                {% for contact in contacts %}
                    <tr>
                        <td class="nowrap">
                            {{ contact.name }}
                        </td>
                        <td class="text-center nowrap">
                            {{ contact.phone }}
                        </td>
                        <td class="text-center">
                            {{ contact.email }}
                        </td>
                        <td class="text-center">
                            {{ contact.is_customer|yesno:"Zákazník," }}
                            {{ contact.get_skills_text }}
                            {{ contact.account|yesno:"+login," }}
                        </td>
                        <td class="text-center">
                            <a class="button tiny no-margin-bottom" href="{% url 'contact:contact-update' pk=contact.id %}">Změnit</a>
                        </td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

<!--     <div class="row">
        <div class="large-12 columns">
            <ul class="pagination">
                {% if paginator.has_previous %}
                <li class="arrow"><a href="?page={{ paginator.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                {% for pg in paginator.page_range %}
                <li{% if pg == paginator.number %} class="current"{% endif %}><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% endfor %}
                {% if paginator.has_next %}
                <li class="arrow"><a href="?page={{ paginator.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
 -->
{% endblock %}