src/stock/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from django.views.generic.list import ListView
# from rest_framework import routers

from stock import views as stock_views
from .models import Item

################################################################################

# router = routers.SimpleRouter()
# router.register(r'stock', login_required(stock_views.StockViewSet))


urlpatterns = patterns('stock.views',
    url(r'^stock/?$', login_required(ListView.as_view(
        model = Item,
        # paginate_by = 2,
        queryset = Item.objects.all(),
        context_object_name = 'items',
        template_name = 'stock/item_list.html',
        )), name="list"),

    url(r'^stock-item/add/?$', login_required(stock_views.ItemCreate.as_view()), name="item-create"),
    # url(r'^stock/(?P<pk>[0-9]+)$', login_required(event_views.EventDetail.as_view()), name="item-detail"),
    url(r'^stock-item/(?P<pk>[0-9]+)/update$', login_required(stock_views.ItemUpdate.as_view()), name="item-update"),
    url(r'^stock-item/(?P<pk>[0-9]+)/delete$', login_required(stock_views.ItemDelete.as_view()), name="item-delete"),


    # url(r'^api2/', include(router.urls)),
    url(r'^api/stock/?$', login_required(stock_views.ItemListAPIView.as_view()), name="api-stock-items"),
    url(r'^api/stock/(?P<pk>[0-9]+)/?$', login_required(stock_views.ItemRetrieveAPIView.as_view()), name="api-stock-item"),

    # url(r'^api/event/(?P<event_pk>[0-9]+)/item/?$', login_required(event_views.EventItemListCreateView.as_view()), name="api-event-item-create"),
    # url(r'^api/event/(?P<event_pk>[0-9]+)/item/(?P<pk>\d+)/?$', login_required(event_views.EventItemRetrieveUpdateDestroyView.as_view()), name="api-event-item-update")



)

src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth import urls as auth_urls

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('account.urls', namespace='account')),
    url(r'', include('event.urls', namespace='event')),
    url(r'', include('stock.urls', namespace='stock')),
    url(r'', include('contact.urls', namespace='contact')),

)\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/stock/models.py
from django.db import models
from base.models import BaseModel

ITEM_DEPENDENCY_SEVERITY_MUST = 1
ITEM_DEPENDENCY_SEVERITY_ADVISE = 2

ITEM_DEPENDENCY_SEVERITY_CHOICES = (
    (ITEM_DEPENDENCY_SEVERITY_MUST, 'nutnost'),
    (ITEM_DEPENDENCY_SEVERITY_ADVISE, 'doporučení'),
)

ITEM_DEPENDENCY_SOLUTION_ALL = 1
ITEM_DEPENDENCY_SOLUTION_ANY = 2

ITEM_DEPENDENCY_SOLUTION_CHOICES = (
    (ITEM_DEPENDENCY_SOLUTION_ALL, 'vyžadovány všechny položky'),
    (ITEM_DEPENDENCY_SOLUTION_ANY, 'vyžadována alespoň jedna položka'),
)

class Category(models.Model):
    name = models.CharField(unique=True, max_length=200, verbose_name="název")
    position = models.IntegerField(verbose_name="pořadí")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "kategorie"
        verbose_name_plural = "kategorie"
        ordering = ('position', )


class Item(BaseModel):
    category = models.ForeignKey(Category, blank=True, on_delete=models.SET_NULL, null=True, verbose_name="kategorie")
    name = models.CharField(unique=True, max_length=200, verbose_name="pracovní název")
    # proposal_name = models.CharField(blank=True, verbose_name="název do nabídky")
    # proposal_default = models.BooleanField
    stock_count = models.SmallIntegerField(default=0, verbose_name="počet kusů celkem")
    # weight = models.FloatField
    # picture = models.ImageField
    # description = models.TextField

    def get_str(self):
        if self.category: return "%s — %s" % (self.category.name, self.name)
        return self.name

    def dependencies_count(self):
        return self.dependencies.all().count()
    dependencies_count.short_description = "počet závislostí"

    class Meta:
        verbose_name = "položka materiálu"
        verbose_name_plural = "materiál"
        ordering = ('category__position', 'name',)


class ItemDependency(BaseModel):
    name = models.CharField(unique=True, max_length=200, verbose_name="název")
    severity = models.PositiveSmallIntegerField(choices=ITEM_DEPENDENCY_SEVERITY_CHOICES, default=ITEM_DEPENDENCY_SEVERITY_MUST, verbose_name="důležitost")
    # description = models.CharField(max_length=500, blank=True, verbose_name="popis")
    dependent_items = models.ManyToManyField(Item, blank=True, related_name='dependencies', verbose_name="použít pro položky")
    solution_type = models.PositiveSmallIntegerField(choices=ITEM_DEPENDENCY_SOLUTION_CHOICES, default=ITEM_DEPENDENCY_SOLUTION_ALL, verbose_name="typ řešení", help_text="Co je třeba splnit k vyřešení závislosti.")
    solution_items = models.ManyToManyField(Item, blank=True, related_name='solved_dependencies', verbose_name="vyžadované položky")

    def __str__(self):
        return self.name

    def dependent_items_count(self):
        return self.dependent_items.all().count()
    dependent_items_count.short_description = "počet použití"

    def solution_items_count(self):
        return self.solution_items.all().count()
    solution_items_count.short_description = "počet řešení"


    class Meta:
        verbose_name = "závislost položky"
        verbose_name_plural = "závislosti položek"
        ordering = ('severity', 'name')

src/stock/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = [
            'category',
            'name',
            'stock_count',
        ]

src/stock/views.py
# from django.shortcuts import render, redirect
# from django.views.generic import TemplateView #, View #, DetailView, View
# from django.views.generic.edit import UpdateView
from rest_framework import generics
# from rest_framework import permissions, viewsets
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import ItemForm
from .models import Item
from .serializers import ItemSerializer


# class StockView(TemplateView):
#     template_name = "list.html"

#     def get_context_data(self, **kwargs):
#         kwargs = super(StockView, self).get_context_data(**kwargs)

#         kwargs.update({
#             "items": Item.objects.all(),
#         })

#         return kwargs





class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('stock:list')

    def delete(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object and then
        redirects to the success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = True
        self.object.save_by(request.user.username)
        return HttpResponseRedirect(success_url)


class ItemCreate(CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('stock:list')

    def form_valid(self, form):
        form.instance.changed_by = self.request.user.username
        return super(ItemCreate, self).form_valid(form)


class ItemUpdate(UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('stock:list')


    def form_valid(self, form):
        form.instance.changed_by = self.request.user.username
        return super(ItemUpdate, self).form_valid(form)







class ItemListAPIView(generics.ListAPIView):
    serializer_class = ItemSerializer

    def get_queryset(self):
        return Item.objects.all()


class ItemRetrieveAPIView(generics.RetrieveAPIView):
    serializer_class = ItemSerializer

    def get_queryset(self):
        return Item.objects.filter(id=self.kwargs['pk'])


# class StockViewSet(viewsets.ModelViewSet):
#     queryset = Item.objects.all()
#     serializer_class = ItemSerializer

#     def get_permissions(self):
#         return (permissions.AllowAny(), )
#         # if self.request.method in permissions.SAFE_METHODS:
#         #     return (permissions.AllowAny(), )
#         # return (permissions.IsAuthenticated(), IsAuthorOfPost(), )

#     # def perform_create(self, serializer):
#     #     instance = serializer.save(author=self.request.user)

#     #     return super(PostViewSet, self).perform_create(serializer)

src/stock/templates/stock/item_confirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles  %}

{% block title %}{{ item.name }}{% endblock %}


{% block content %}
    <div class="row">
        <div class="large-12 columns">
        <h1>{{ item.name }}</h1>
        </div>
    </div>

    <form action="" method="post">{% csrf_token %}
        <div class="row">
            <div class="large-8 large-offset-2 medium-10 medium-offset-1 columns">
                <p>Opravdu chcete tuto položku smazat?</p>
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns">
                <div class="right">
                    <button type="submit" class="right button alert">Smazat</button>
                    <a href="{% url 'stock:list' %}" class="button secondary">Zrušit</a>
                </div>
            </div>
        </div>
    </form>


{% endblock %}

src/stock/templates/stock/item_form.html
{% extends "base.html" %}
{% load static from staticfiles  %}

{% block title %}{% if item %}{{ item.name }} &ndash; upravit materiál{% else %}Přidat materiál{% endif %}{% endblock %}


{% block content %}
    <div class="row">
        <div class="large-12 columns">

        {% if item %}
        <h1>{{ item.name }} &ndash; upravit materiál</h1>
        {% else %}
        <h1>Přidat materál</h1>
        {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
        <form action="{% if item %}{% url 'stock:item-update' pk=item.id %}{% else %}{% url 'stock:item-create' %}{% endif %}" method="post">
            {% csrf_token %}

            <div class="row">
                <div class="large-8 large-offset-2 medium-10 medium-offset-1 columns">

                {% if form.non_field_errors %}
                    <div class="alert-box warning">
                        {{ form.non_field_errors|join:"<br>" }}
                    </div>
                {% endif %}

                <table class="form topped wide">
                    <tr>
                        <th colspan="2">
                            {{ form.name.label_tag }}
                        </th>
                    </tr>
                    <tr>
                        <td colspan="2">
                            {{ form.name }}
                            {% if form.name.errors %}
                                <div class="alert-box warning">
                                    {{ form.name.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <th>
                            {{ form.stock_count.label_tag }}
                        </th>
                        <th>
                            {{ form.category.label_tag }}
                        </th>
                    </tr>
                    <tr>
                        <td class="nowrap" width="30%">
                            {{ form.stock_count }}
                            {% if form.stock_count.errors %}
                                <div class="alert-box alert">
                                    {{ form.stock_count.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                        <td>
                            {{ form.category }}
                            {% if form.category.errors %}
                                <div class="alert-box warning">
                                    {{ form.category.errors|join:"<br>" }}
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                </table>

                </div>
            </div>

            <div class="right">
                <button type="submit" class="right button success">Uložit</button>
                <a href="{% url 'stock:list' %}" class="button secondary">Zrušit</a>
            </div>
            {% if item %}
            <div class="left">
                <a href="{% url 'stock:item-delete' pk=item.id %}" class="tiny button alert">Smazat</a>
            </div>
            {% endif %}
        </form>
        </div>
    </div>


    {% if item %}
    <div class="row text-right">
        <div class="large-12 columns">
        <p><small>Naposledy položku upravil {{ item.changed_at|date:"j. n. Y H:i" }} uživatel {{ item.changed_by }}.</small></p>
        </div>
    </div>
    {% endif %}


{% endblock %}

src/stock/templates/stock/item_list.html
{% extends "base.html" %}
{% load static from staticfiles  %}


{% block title %}Sklad materiálu{% endblock %}




{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <div class="right">
                <a href="{% url 'stock:item-create' %}" class="button success">Přidat položku</a>
            </div>
            <h1>Sklad materiálu</h1>
        </div>
    </div>

    <div class="row">
        <div class="large-8 large-offset-2 medium-10 medium-offset-1 columns">


            <table class="wide">
                {% for item in items %}
                    {% ifchanged item.category %}
                    {% if item.category.name %}
                    <tr>
                        <th colspan="3">
                            <h3>{{ item.category.name|default:"" }}</h3>
                        </th>
                    </tr>
                    {% else %}
                    <tr>
                        <th>
                            Kategorie / Položka
                        </th>
                        <th class="text-center">
                            Celkem ve&nbsp;skladu
                        </th>
                        <th class="text-center">
                            Změnit
                        </th>
                    </tr>
                    {% endif %}
                    {% endifchanged %}

                    <tr>
                        <td class="wide">
                            {{ item.name }}
                        </td>
                        <td class="text-center">
                            {{ item.stock_count }}
                        </td>
                        <td class="text-center">
                            <a class="button tiny no-margin-bottom" href="{% url 'stock:item-update' pk=item.id %}">Změnit</a>
                        </td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

<!--     <div class="row">
        <div class="large-12 columns">
            <ul class="pagination">
                {% if paginator.has_previous %}
                <li class="arrow"><a href="?page={{ paginator.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                {% for pg in paginator.page_range %}
                <li{% if pg == paginator.number %} class="current"{% endif %}><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% endfor %}
                {% if paginator.has_next %}
                <li class="arrow"><a href="?page={{ paginator.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
 -->
{% endblock %}