src/event/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from event import views as event_views

################################################################################


urlpatterns = patterns('event.views',
    url(r'^$', login_required(event_views.DashboardView.as_view()), name="dashboard"),
    url(r'^set-dashboard-start/(?P<date_arg>\d{4}-\d{2}-\d{2})$', login_required(event_views.setDashboardStart), name="set-dashboard-start"),
    url(r'^set-dashboard-end/(?P<date_arg>\d{4}-\d{2}-\d{2})$', login_required(event_views.setDashboardEnd), name="set-dashboard-end"),
    url(r'^reset-dashboard-dates$', login_required(event_views.resetDashboardDates), name="reset-dashboard-dates"),
    url(r'^event-add/(?P<start>\d{4}-\d{2}-\d{2})?$', login_required(event_views.EventCreate.as_view()), name="event-create"),
    # url(r'^event/(?P<pk>[0-9]+)$', login_required(event_views.eventDetail), name="event-detail"),
    url(r'^event/(?P<pk>[0-9]+)$', login_required(event_views.EventDetail.as_view()), name="event-detail"),
    url(r'^event/(?P<pk>[0-9]+)/update$', login_required(event_views.EventUpdate.as_view()), name="event-update"),
    url(r'^event/(?P<pk>[0-9]+)/delete$', login_required(event_views.EventDelete.as_view()), name="event-delete"),
    url(r'^event/(?P<pk>[0-9]+)/items$', login_required(event_views.EventItemList.as_view()), name="event-items"),
    url(r'^event/(?P<pk>[0-9]+)/book-all-possible$', login_required(event_views.bookAllPossible), name="book-all-possible"),

    # url(r'^event/(?P<pk>[0-9]+)/items$', login_required(event_views.EventItemList.as_view()), name="event-items"),
    # url(r'^event/(?P<pk>[0-9]+)/items$', login_required(event_views.EventItemList.as_view()), name="event-items"),

    # url(r'^event/(?P<pk>[0-9]+)/items/api/event/?$', event_views.EventItemListCreateView.as_view(), name="event-item-list-create"),
    # url(r'^event/(?P<pk>[0-9]+)/items/api/event/(?P<pk>\d+)/?$', event_views.EventItemView.as_view(), name="event-item-list-create")

    url(r'^api/event/(?P<event_pk>[0-9]+)/item/?$', login_required(event_views.EventItemListCreateView.as_view()), name="api-event-item-create"),
    url(r'^api/event/(?P<event_pk>[0-9]+)/item/(?P<pk>\d+)/?$', login_required(event_views.EventItemRetrieveUpdateDestroyView.as_view()), name="api-event-item-update")

)

src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth import urls as auth_urls

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('account.urls', namespace='account')),
    url(r'', include('event.urls', namespace='event')),
    url(r'', include('stock.urls', namespace='stock')),
    url(r'', include('contact.urls', namespace='contact')),

)\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/stock/models.py
from django.db import models
from base.models import BaseModel

ITEM_DEPENDENCY_SEVERITY_MUST = 1
ITEM_DEPENDENCY_SEVERITY_ADVISE = 2

ITEM_DEPENDENCY_SEVERITY_CHOICES = (
    (ITEM_DEPENDENCY_SEVERITY_MUST, 'nutnost'),
    (ITEM_DEPENDENCY_SEVERITY_ADVISE, 'doporučení'),
)

ITEM_DEPENDENCY_SOLUTION_ALL = 1
ITEM_DEPENDENCY_SOLUTION_ANY = 2

ITEM_DEPENDENCY_SOLUTION_CHOICES = (
    (ITEM_DEPENDENCY_SOLUTION_ALL, 'vyžadovány všechny položky'),
    (ITEM_DEPENDENCY_SOLUTION_ANY, 'vyžadována alespoň jedna položka'),
)

class Category(models.Model):
    name = models.CharField(unique=True, max_length=200, verbose_name="název")
    position = models.IntegerField(verbose_name="pořadí")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "kategorie"
        verbose_name_plural = "kategorie"
        ordering = ('position', )


class Item(BaseModel):
    category = models.ForeignKey(Category, blank=True, on_delete=models.SET_NULL, null=True, verbose_name="kategorie")
    name = models.CharField(unique=True, max_length=200, verbose_name="pracovní název")
    # proposal_name = models.CharField(blank=True, verbose_name="název do nabídky")
    # proposal_default = models.BooleanField
    stock_count = models.SmallIntegerField(default=0, verbose_name="počet kusů celkem")
    # weight = models.FloatField
    # picture = models.ImageField
    # description = models.TextField

    def get_str(self):
        if self.category: return "%s — %s" % (self.category.name, self.name)
        return self.name

    def dependencies_count(self):
        return self.dependencies.all().count()
    dependencies_count.short_description = "počet závislostí"

    class Meta:
        verbose_name = "položka materiálu"
        verbose_name_plural = "materiál"
        ordering = ('category__position', 'name',)


class ItemDependency(BaseModel):
    name = models.CharField(unique=True, max_length=200, verbose_name="název")
    severity = models.PositiveSmallIntegerField(choices=ITEM_DEPENDENCY_SEVERITY_CHOICES, default=ITEM_DEPENDENCY_SEVERITY_MUST, verbose_name="důležitost")
    # description = models.CharField(max_length=500, blank=True, verbose_name="popis")
    dependent_items = models.ManyToManyField(Item, blank=True, related_name='dependencies', verbose_name="použít pro položky")
    solution_type = models.PositiveSmallIntegerField(choices=ITEM_DEPENDENCY_SOLUTION_CHOICES, default=ITEM_DEPENDENCY_SOLUTION_ALL, verbose_name="typ řešení", help_text="Co je třeba splnit k vyřešení závislosti.")
    solution_items = models.ManyToManyField(Item, blank=True, related_name='solved_dependencies', verbose_name="vyžadované položky")

    def __str__(self):
        return self.name

    def dependent_items_count(self):
        return self.dependent_items.all().count()
    dependent_items_count.short_description = "počet použití"

    def solution_items_count(self):
        return self.solution_items.all().count()
    solution_items_count.short_description = "počet řešení"


    class Meta:
        verbose_name = "závislost položky"
        verbose_name_plural = "závislosti položek"
        ordering = ('severity', 'name')

src/event/forms.py
from django import forms

from .models import Event

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = [
            'name',
            'customer',
            'manager',
            'start',
            'end',
            'remark',
        ]


    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        start_date = self.cleaned_data.get("start")
        end_date = self.cleaned_data.get("end")
        if start_date and end_date and end_date < start_date:
            raise forms.ValidationError("Start akce musí být dřív, než konec")
        return cleaned_data

src/event/views.py
from datetime import date, timedelta
import dateutil.parser

from rest_framework import generics, status
from rest_framework.response import Response

from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView  # View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from stock.models import Item

from .models import Event, EventItem
from .forms import EventForm
from .serializers import EventItemSerializer, EventItemSimpleSerializer



def setDashboardStart(request, date_arg):
    request.session['dashboard_start'] = date_arg
    return redirect('event:dashboard')


def setDashboardEnd(request, date_arg):
    request.session['dashboard_end'] = date_arg
    return redirect('event:dashboard')


def resetDashboardDates(request):
    if request.session.get('dashboard_start'): del request.session['dashboard_start']
    if request.session.get('dashboard_end'): del request.session['dashboard_end']
    return redirect('event:dashboard')


def bookAllPossible(request, pk):
    event = get_object_or_404(Event, pk=pk)
    total_booked_count = 0
    for eventitem in event.eventitem_set.all():
        if eventitem.to_be_booked_count > 0:
            if eventitem.available_count > 0:
                eventitem.booked_count = eventitem.available_count
                eventitem.save()
                messages.success(request, "Zamluveno: %s %d×" % (eventitem.item.name, eventitem.booked_count))
                total_booked_count += eventitem.booked_count
    if total_booked_count == 0:
        messages.warning(request, "Nebylo možné zarezervovat žádnou položku")
    return redirect('event:event-detail', pk=pk)



class DashboardView(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        kwargs = super(DashboardView, self).get_context_data(**kwargs)

        # get from/to from session or set default
        show_reset_dates = False
        dashboard_start = self.request.session.get("dashboard_start", None)
        if dashboard_start is None:
            dashboard_start = date.today() - timedelta(days=settings.DASHBOARD_DEFAULT_DAYS_HISTORY)
        else:
            dashboard_start = dateutil.parser.parse(dashboard_start).date()
            show_reset_dates = True

        dashboard_end = self.request.session.get("dashboard_end", None)
        if dashboard_end is None:
            dashboard_end = date.today() + timedelta(days=settings.DASHBOARD_DEFAULT_DAYS_FUTURE)
        else:
            dashboard_end = dateutil.parser.parse(dashboard_end).date()
            show_reset_dates = True


        events_queryset = Event.objects.filter(start__lt=dashboard_end, end__gt=dashboard_start).order_by('start', '-end')#.select_related('manager')
        # use events as stack
        events = list(events_queryset)


        # generate rows of calendar
        cal = []

        d = dashboard_start
        day_strings = ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne']
        weekdays = set([5, 6])
        while d <= dashboard_end:
            cal.append({'date': d, 'day': day_strings[d.weekday()], 'weekend': d.weekday() in weekdays, 'cols':[]})
            d += timedelta(days=1)

        total_rows = (dashboard_end - dashboard_start).days + 1

        # assign events to columns
        # assign columns to rows, each event has proper rowspan
        c = 1 # col pointer starts with second column, first contains dates
        while len(events):
            next_events = [] # helper list for event that could not be assignet do current column
            r = 0 # row pointer

            try:

                while r < total_rows:
                    rundown = False
                    runoff = False
                    e = events.pop(0)
                    # event started before cal
                    if e.start < dashboard_start:
                        e.start = dashboard_start
                        rundown = True
                    # event ends after cal
                    if e.end > dashboard_end:
                        e.end = dashboard_end
                        runoff = True
                    # if can not use this column for this event, events are over lapsing
                    if e.start < cal[r]['date']:
                        # postpone it to next column
                        next_events.append(e)
                        # start over to pick the next one
                        continue
                    # skip rows until row date and event start date are equal
                    while cal[r]['date'] < e.start:
                        cal[r]['cols'].append({'empty': True})
                        r += 1

                    # cal[r]['date'] == e.start at this point if data not corrupted
                    # assign event to col
                    cal[r]['cols'].append({'event': e, 'rundown': rundown, 'runoff': runoff, 'rowspan': e.length})
                    r += 1
                    # skip rows according to event length
                    while cal[r]['date'] <= e.end:
                        cal[r]['cols'].append(None)
                        r += 1

                # runned out all rows, append any leftover of events to next_events
                next_events += events

            except IndexError:
                # events is empty
                # pass
                # fill rest of the rows by empty values
                while r < total_rows and cal[r]['date'] <= dashboard_end:
                    cal[r]['cols'].append({'empty': True})
                    r += 1

            finally:
                # try use leftovers in next_events
                events = next_events

            # proceed to the next column
            c += 1

        kwargs.update({
            "events": events_queryset,
            "cal": cal,
            "today": date.today(),
            "dashboard_start": dashboard_start,
            "dashboard_end": dashboard_end,
            "show_reset_dates": show_reset_dates,
        })

        return kwargs


# def eventDetail(request, pk):
#     event = Event.objects.get(id=pk)

#     return render(request, 'event/event_detail.html', {
#         'event': event
#     })

class EventDetail(DetailView):
    queryset = Event.objects.all().prefetch_related('eventitem_set__item__dependencies').select_related('customer', 'manager')


class EventDelete(DeleteView):
    model = Event
    success_url = reverse_lazy('event:dashboard')

    def delete(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object and then
        redirects to the success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = True
        self.object.save_by(request.user.username)
        return HttpResponseRedirect(success_url)


class EventCreate(CreateView):
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        form.instance.changed_by = self.request.user.username
        return super(EventCreate, self).form_valid(form)

    def get_initial(self):
        if not 'start' in self.kwargs or not self.kwargs['start']:
            return {}
        d = "%(d)s.%(m)s.%(y)s" % {
            'd':self.kwargs['start'].split('-')[2],
            'm':self.kwargs['start'].split('-')[1],
            'y':self.kwargs['start'].split('-')[0]
        }
        return { 'start': d, 'end': d }

class EventUpdate(UpdateView):
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        form.instance.changed_by = self.request.user.username
        return super(EventUpdate, self).form_valid(form)


class EventItemList(ListView):
    model = EventItem
    # form_class = EventForm

    def get_queryset(self):
        self.event = get_object_or_404(Event, pk=self.kwargs['pk'])
        return EventItem.objects.filter(event=self.event)

    def get_context_data(self, **kwargs):
        kwargs = super(EventItemList, self).get_context_data(**kwargs)

        # print(self.__dict__)
        # event = Event.objects.get(pk=self.kwargs['pk'])

        # print('ahoj')
        # print(self.event.items)
        kwargs.update({
            "event": self.event,
            "stock_items": Item.objects.all()
        })

        return kwargs




class EventItemListCreateView(generics.ListCreateAPIView):
    serializer_class = EventItemSerializer

    def get_queryset(self):
        self.event = get_object_or_404(Event, pk=self.kwargs['event_pk'])
        return EventItem.objects.filter(event=self.event)

    def post(self, request, **kwargs):
        request.DATA['event'] = self.kwargs['event_pk']
        request.DATA['item'] = request.DATA['item_id']
        serializer = EventItemSerializer(data = request.DATA, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class EventItemRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = EventItemSimpleSerializer
    queryset = EventItem.objects.all()


# #TODO procistit
# from rest_framework import permissions, viewsets

# # from .models import EventItem
# from .permissions import CanEditItems
# from .serializers import EventItemSerializer

# class EventItemViewSet(viewsets.ModelViewSet):
#     queryset = EventItem.objects.all()
#     serializer_class = EventItemSerializer

#     def get_permissions(self):
#         if self.request.method in permissions.SAFE_METHODS:
#             return (permissions.AllowAny(), )
#         return (permissions.IsAuthenticated(), CanEditItems(), )

src/event/templates/event/event_confirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles  %}

{% block title %}{{ event.name }}{% endblock %}


{% block content %}
    <div class="row">
        <div class="large-12 columns">
        <h1>{{ event.name }}</h1>
        <h3 class="subheader">{{ event.start|date:"j. n. Y" }} &mdash; {{ event.end|date:"j. n. Y" }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="large-6 large-offset-3 medium-8 medium-offset-2 columns">

            <table class="wide">
                <tr>
                    <th>
                        Zákazník:
                    </th>
                    <td class="wide">
                        {% if event.customer %}TODO {{ event.customer.name }} &ndash; {{ event.customer.phone }} &ndash; <a href="mailto:{{ event.customer.email }}">{{ event.customer.email }}</a>{% else %}<small>nevyplněno</small>{% endif %}
                    </td>
                </tr>
                <tr>
                    <th>
                        Zodpovídá:
                    </th>
                    <td>
                        {% if event.manager %}{{ event.manager.name }} &ndash; {{ event.manager.phone }} &ndash; <a href="mailto:{{ event.manager.email }}">{{ event.manager.email }}</a>{% else %}<small>nevyplněno</small>{% endif %}
                    </td>
                </tr>
                <tr>
                    <th>
                        Poznámka:
                    </th>
                    <td>
                        {% if event.remark %}{{ event.remark|linebreaksbr }}{% else %}<small>nevyplněno</small>{% endif %}
                    </td>
                </tr>
            </table>

        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <form action="" method="post">{% csrf_token %}
                <div class="row">
                    <div class="large-6 large-offset-3 medium-8 medium-offset-2 columns">

                        <p>Opravdu chcete tuto akci smazat?</p>

                    </div>
                </div>

                <div class="right">
                    <button type="submit" class="right button alert">Smazat</button>
                    <a href="{% url 'event:event-update' pk=event.id %}" class="button secondary">Zrušit</a>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
        </div>
    </div>

{% endblock %}

src/event/templates/event/event_detail.html
{% extends "base.html" %}
{% load static from staticfiles  %}

{% block title %}{{ event.name }}{% endblock %}

{% block endstatic %}
    {{ block.super }}
    <script type="text/javascript" async defer>
        jQuery(".js-confirm").on("click", function(e){
            var btn = jQuery(this);
            if (confirm("Opravdu chcete smazat akci?")){
                console.log(btn);
            } else {
                e.preventDefault();
            }
        });


        $(document).ready(function(e) {
            $('.toggle-details').each(function(i) {
                var tid = $(this).attr('data-toggle')
                $(this).click(function(e) {
                    $('#'+tid).slideToggle('fast');
                });
                $('#'+tid).hide();
            });
        });
    </script>

{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <h1>{{ event.name }}</h1>
            <div class="right">
                <a href="{% url 'event:event-update' pk=event.id %}" class="right small button">Upravit akci</a>
                <a href="{% url 'event:dashboard' %}" class="small button secondary">Zpět</a>
            </div>
            <h3 class="subheader">{{ event.start|date:"j. n. Y" }} &mdash; {{ event.end|date:"j. n. Y" }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
        </div>
    </div>
    <div class="row">
        <div class="medium-10 medium-offset-1 columns">

            <table class="topped wide">
                <tr>
                    <th>
                        Zákazník:
                    </th>
                    <td{% if event.customer.is_deleted%} class="is_deleted"{% endif %}>
                        {% if event.customer %}{{ event.customer.name }} &ndash; {{ event.customer.phone }}{% else %}<small>nevyplněno</small>{% endif %}
                    </td>
                </tr>
                <tr>
                    <th>
                        Zodpovídá:
                    </th>
                    <td{% if event.manager.is_deleted%} class="is_deleted"{% endif %}>
                        {% if event.manager %}{{ event.manager.name }} &ndash; {{ event.manager.phone }}{% else %}<small>nevyplněno</small>{% endif %}
                    </td>
                </tr>
                <tr>
                    <th>
                        Poznámka:
                    </th>
                    <td class="wide">
                        {% if event.remark %}{{ event.remark|linebreaksbr }}{% else %}<small>nevyplněno</small>{% endif %}
                    </td>
                </tr>
            </table>

        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">

            <h2>Materiál</h2>
        </div>
    </div>


    <div class="row">
        <div class="medium-10 medium-offset-1 columns">
            {% if event.items.all|length == 0 %}
            <p><small>zatím žádný materiál</small></p>

            {% else %}
            <p><small>Rozpis značí počet kusů materiálu, který je třeba na akci mít s sebou. Zamluvený počet je blokování položky vůči ostatním akcím. Blokace je na celý den akce.</small></p>

            <table class="wide">
                <tr>
                    <th>
                        položka
                    </th>
                    <th>
                        rozpis /&nbsp;zamluveno
                    </th>
                    <th>
                        k&nbsp;dispozici /&nbsp;pro&nbsp;ostatní /&nbsp;celkem
                    </th>
<!--                     <th>
                        třeba zamluvit
                    </th>
                    <th>
                        chybí!
                    </th>
 -->
                </tr>
                {% for event_item in event.eventitem_set.all %}
                <tr>
                    <td class="{% if event_item.item.is_deleted %}is_deleted{% endif %}">
                        <span{% if event_item.item.is_deleted %} title="Tato položka byla odstraněna ze skladu"{% endif %}>{{ event_item.item.name }}</span>
                    </td>
                    <td class="text-center">
                        <span class="label {% if event_item.booked_count == event_item.requested_count %}success{% else %}warning{% endif %}">{{ event_item.requested_count }} /
                        {{ event_item.booked_count }}
                        </span>
                    </td>
                    <td class="text-center">
                        <strong>{{ event_item.available_count }}</strong> / {% if event_item.to_be_booked_by_others_count > 0 %}{{ event_item.to_be_booked_by_others_count }}{% else %}0{% endif %} /
                        {{ event_item.item.stock_count }}
                    </td>
<!--                     <td class="text-center">
                        {% if event_item.to_be_booked_count > 0 %}<span class="label">{{ event_item.to_be_booked_count }}</span>{% else %}0{% endif %}
                    </td>
                    <td class="text-center">
                        {% if event_item.missing_count > 0 %}<span class="alert label">{{ event_item.missing_count }}</span>{% else %}0{% endif %}
                    </td>
 -->                </tr>
                {% endfor %}
            </table>


            <div class="right">
                <a href="{% url 'event:book-all-possible' pk=event.id %}" class="small button success">Zamluvit co jde</a>
            </div>
            {% endif %}

            <div class="right">
                <a href="{% url 'event:event-items' pk=event.id %}" class="small button">Upravit materiál</a>
            </div>

        </div>
    </div>


    {% if event.get_dependencies|length > 0 %}
    <div class="row">
        <div class="medium-10 medium-offset-1 columns">
            <h3>Kontrola materiálu</h3>

            <p><small>Každá položka může mít své závislosti, ty jsou vyhodnoceny zvlášť pro rozpis a zvlášť pro zamluvené položky. Sleduje se, zda je potřebných položek alespoň tolik, kolik jich závislost vyvolalo. Vykřičník označuje povinné závislosti. Kliknutím na název se zobrazí podrobnosti.</small></p>

            <table class="topped wide">
                <tr>
                    <th>
                        Název závislosti
                    </th>
                    <th>
                        rozpis
                    </th>
                    <th>
                        zamluveno
                    </th>
                </tr>
                {% for dependency_row in event.get_dependencies %}
                <tr>
                    <td class="wide">
                        <span class="toggle-details" data-toggle="toggle_{{ forloop.counter }}">{{ dependency_row.dependency.name }}{% if dependency_row.must %} <span class="label" title="Toto je povinná závislost">!</span>{% endif%}</span><br>

                        <table class="wide" id="toggle_{{ forloop.counter }}" style="display: none;">
                        <tr>
                    <td>
                        Zdroj <strong>{{ dependency_row.requested_source_count }}</strong> / {{ dependency_row.booked_source_count }}<br /><small>rozpis / zamluveno</small>
                        {% for i in dependency_row.dependent_items %}
                            {% if forloop.first %}
                            <ul>
                            {% endif %}
                                <li><small{% if i.item.is_deleted %} title="Tato položka byla odstraněna ze skladu" class="is_deleted"{% endif %}>{{ i.item.name }} <strong>{{ i.requested_count}}</strong> / {{ i.booked_count}}</small></li>
                            {% if forloop.last %}
                            </ul>
                            {% endif %}
                        {% empty %}
                            <small>Žádná definovaná položka</small>
                        {% endfor %}
                    </td>
                    <td>
                        &rarr;
                    </td>
                    <td>
                        Řešení <strong>{{ dependency_row.requested_solution_count }}</strong> / {{ dependency_row.booked_solution_count }}<br /><small>rozpis/zamluveno</small><br />
                        <small>{{ dependency_row.dependency.get_solution_type_display|capfirst }}.</small><br />
                        {% for i in dependency_row.solution_items %}
                            {% if forloop.first %}
                            <ul>
                            {% endif %}
                                <li><small{% if i.item.is_deleted %} title="Tato položka byla odstraněna ze skladu" class="is_deleted"{% endif %}>{{ i.item.name }} <strong>{{ i.requested_count}}</strong> / {{ i.booked_count}}</small></li>
                            {% if forloop.last %}
                            </ul>
                            {% endif %}
                        {% empty %}
                            <small>Žádná definovaná položka</small>
                        {% endfor %}
                    </td>
                    </tr>
                    </table>


                    </td>
                    <td class="text-center nowrap">
                        {% if dependency_row.requested_solved %}
                            <span class="label {% if dependency_row.requested_source_count > dependency_row.requested_solution_count%}warning{% else %}success{% endif %}" title="{% if dependency_row.must %}Povinná závislost{% else %}Doporučená závislost{% endif %}">OK</span>
                        {% else %}
                            {% if dependency_row.must %}
                            <span class="label alert" title="Povinná závislost">ERR</span>
                            {% else %}
                            <span class="label warning" title="Doporučená závislost">ERR</span>
                            {% endif %}
                        {% endif %}
                        <br />
                        <small>{{ dependency_row.requested_source_count }} &rarr; {{ dependency_row.requested_solution_count }}</small>
                    </td>
                    <td class="text-center nowrap">
                        {% if dependency_row.booked_source_count == 0 %}
                            <span class="label secondary" title="Není zamluveno">N/A</span>
                        {% else %}
                            {% if dependency_row.booked_solved %}
                                <span class="label {% if dependency_row.booked_source_count > dependency_row.booked_solution_count%}warning{% else %}success{% endif %}" title="{% if dependency_row.must %}Povinná závislost{% else %}Doporučená závislost{% endif %}">OK</span>
                            {% else %}
                                {% if dependency_row.must %}
                                <span class="label alert" title="Povinná závislost">ERR</span>
                                {% else %}
                                <span class="label warning" title="Doporučená závislost">ERR</span>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                        <br />
                        <small>{{ dependency_row.booked_source_count }} &rarr; {{ dependency_row.booked_solution_count }}</small>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% endif %}



    <div class="row">
        <div class="large-12 columns text-right">
            <p><small>Naposledy akci upravil {{ event.changed_at|date:"j. n. Y H:i" }} uživatel {{ event.changed_by }}.</small></p>
        </div>
    </div>


{% endblock %}